### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Gluneklairo** [hushenghao/NativeTools#2]
在Android 12上，即使隐藏锁屏通知，锁屏时仍然会短暂显示通知图标然后消失，锁屏时钟由单行变双行，体验割裂，希望有办法能解决这个问题

**Comment by hushenghao** [comment]
不同的设备和系统版本行为略有差异，可以参考帮助，将通知的 **锁屏显示给关闭** 即可隐藏锁屏通知
<img width="372" alt="image" src="https://user-images.githubusercontent.com/28776451/178401114-88d6dc87-caf0-4045-97f9-48ab91d5c933.png">
<img width="372" alt="image" src="https://user-images.githubusercontent.com/28776451/178401163-c52d0c2c-9217-42af-9b1c-726b06af597a.png">
