### ISSUE TITLE
How to display network speed in the status bar?

### ISSUE THREAD

**Issue by jcperil** [hushenghao/NativeTools#3]
In google play store, I saw screenshot that the network speed is displayed in the status bar.

<img src="https://user-images.githubusercontent.com/89805719/216618910-32d3f981-b391-49ce-a98e-53ea70996da6.jpg" height="300px"/>

How did you manage to do that? I can't find any settings to achieve that. I can only see it in the notification drawer.

<img src="https://user-images.githubusercontent.com/89805719/216621067-c0a3ccff-a4db-4708-aa8f-ad445d140bdc.jpg" height="300px"/>

**Comment by hushenghao** [comment]
MIUI system needs to turn on the option of "**display icon when there is notification**" in the Settings and change the notification display to **"native style"** to display the normal network speed. If it does not take effect, restart the device or change the theme.

**Comment by jcperil** [comment]
> "display icon when there is notification" in the Settings

I can't find this. I am on MIUI Global. Can you mention the full path?

Settings >> ? >> ? >> Display icon when there is notification.

**Comment by hushenghao** [comment]
![1675469256147](https://user-images.githubusercontent.com/28776451/216733538-2c9201d1-e49c-4eee-823f-9383e7a8c50e.png)

 **If it does not take effect, restart the device or change the theme.**

**Comment by jcperil** [comment]
#### This are the changes I made. I also restarted the device. Please let me know if correct.

![notification icons](https://user-images.githubusercontent.com/89805719/216748301-4a5f4125-0684-45cb-a6e0-f74e3eab5431.jpg)

---
<img src="https://user-images.githubusercontent.com/89805719/216748305-28209dfa-122f-43c7-b554-6bbaacad01ac.jpg" height="300px"/>

---
#### Current behavior
The network speed icon is displayed in the status bar normally.

![net monitor status bar](https://user-images.githubusercontent.com/89805719/216748582-74f789fd-cc6e-4cc4-b303-d6a0f6bd69cd.jpg)

---
But when I pull down notification drawer, network speed disappears from status bar and appears as a notification instead. Is this expected behavior?

<img src="https://user-images.githubusercontent.com/89805719/216748748-be8d5bb5-56f2-44c4-8d39-f4c568d1fd87.jpg" height="300px"/>

**Comment by hushenghao** [comment]
This is a feature of miui, and the app cannot be modified.
