### ISSUE TITLE
[Feature-Request] Make the numbers in the status bar larger, or split them into two blocks (Up/Down)

### ISSUE THREAD

**Issue by marvellz** [hushenghao/NativeTools#5]
Or new versions of Android do not allow this? Once upon a time in [Internet Speed Meter](https://play.google.com/store/apps/developer?id=DynamicApps) this was possible.

![Capture](https://github.com/hushenghao/NativeTools/assets/48913829/f0b66dd8-9fd4-4027-9fbc-b7a943960efc)

Or is it even better to make it not in a circle (not top/bottom), but into a string (line)?

**Comment by hushenghao** [comment]
The network speed is displayed in the notification icon, which is a fixed size square area, and no additional content can be displayed.
The scheme in the image can only be supported by SystemUI.

**Comment by marvellz** [comment]
OK.

Maybe a widget? See how it's done in [Network Speed](https://play.google.com/store/apps/details?id=com.evozi.network).

https://github.com/hushenghao/NativeTools/assets/48913829/228fd30a-7d3b-4520-b932-edc96c6d4434

It has cool flexible settings.

Sorry if I seem intrusive.
