### ISSUE TITLE
[Feature-Request] Ability to disable in the notification bar, display only in the status bar

### ISSUE THREAD

**Issue by marvellz** [hushenghao/NativeTools#6]
![Capture](https://github.com/hushenghao/NativeTools/assets/48913829/cea8884a-68e2-4f05-a7c0-87f70d35b296)

**Comment by hushenghao** [comment]
Can't.
This was a feature in a very old version and has since been removed
https://developer.android.com/about/versions/12/behavior-changes-12#custom-notifications
